version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: newsaggregator-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: newsaggregator
      POSTGRES_PASSWORD: newspassword
      POSTGRES_DB: newsaggregator
    ports:
      - "5433:5432"
    volumes:
      - newsaggregator_db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U newsaggregator" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  newsaggregator_db_data:
    driver: local
